name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Install Node.js, NPM & Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Npm Install
      run: npm install

    - name: build for windows
      run: npm run build:prod
